//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UriShell.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UriShell.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Настройка объекта, полученного через URI &quot;{0}&quot;, уже задана..
        /// </summary>
        internal static string AttemptToOverwriteShellResolveSetupPlayer {
            get {
                return ResourceManager.GetString("AttemptToOverwriteShellResolveSetupPlayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Превышено возможное количество открытых URI..
        /// </summary>
        internal static string NoAvailableUriResolutionId {
            get {
                return ResourceManager.GetString("NoAvailableUriResolutionId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ошибка при открытии файла &apos;{0}&apos;: {1}.
        /// </summary>
        internal static string OpenExternalFileError {
            get {
                return ResourceManager.GetString("OpenExternalFileError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Открыт URI &quot;{0}&quot;.
        /// </summary>
        internal static string ShellResolveOpenComplete {
            get {
                return ResourceManager.GetString("ShellResolveOpenComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Настройка для объекта, полученного через URI &quot;{0}&quot;, не была вызвана из-за несовместимости типов. Ожидалось {1}, а получено {2}..
        /// </summary>
        internal static string ShellResolveSetupAbortedDueToIncompatibility {
            get {
                return ResourceManager.GetString("ShellResolveSetupAbortedDueToIncompatibility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Обнаружена попытка задать null в качестве настройки к URI &quot;{0}&quot;..
        /// </summary>
        internal static string ShellResolveSetupPlayerCannotBeNull {
            get {
                return ResourceManager.GetString("ShellResolveSetupPlayerCannotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Перетаскивание на поддерживается в {0}..
        /// </summary>
        internal static string SidebarPlacementConnectorDoesntSupportDragDrop {
            get {
                return ResourceManager.GetString("SidebarPlacementConnectorDoesntSupportDragDrop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} не поддерживает изменение индекса присоединенного объекта. Подобное действие нецелесообразно для SidebarView..
        /// </summary>
        internal static string SidebarPlacementConnectorDoesntSupportMoveConnected {
            get {
                return ResourceManager.GetString("SidebarPlacementConnectorDoesntSupportMoveConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Невозможно выполнить действие над {0}, т.к. объект сейчас занят..
        /// </summary>
        internal static string UnableToBeginChangePlacementConnector {
            get {
                return ResourceManager.GetString("UnableToBeginChangePlacementConnector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Невозможно разрешить URI, т.к. соответствующий {0} не зарегистрирован..
        /// </summary>
        internal static string UriModuleItemResolverNotFound {
            get {
                return ResourceManager.GetString("UriModuleItemResolverNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Невозможно выполнить размещение объекта, т.к. ни один доступный {0} не принял URI..
        /// </summary>
        internal static string UriPlacementNotFound {
            get {
                return ResourceManager.GetString("UriPlacementNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нет записи объекта {0} на отсоединение от пользовательского интерфейса..
        /// </summary>
        internal static string UriResolvedNotRegisteredForDisconnect {
            get {
                return ResourceManager.GetString("UriResolvedNotRegisteredForDisconnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Объект {0} уже содержится в {1}..
        /// </summary>
        internal static string UriResolvedObjectAlreadyExists {
            get {
                return ResourceManager.GetString("UriResolvedObjectAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Объект {0} не содержится в {1}..
        /// </summary>
        internal static string UriResolvedObjectDoesntExist {
            get {
                return ResourceManager.GetString("UriResolvedObjectDoesntExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Объект с идентификатором {0} не содержится в {1}..
        /// </summary>
        internal static string UriResolvedObjectIdDoesntExist {
            get {
                return ResourceManager.GetString("UriResolvedObjectIdDoesntExist", resourceCulture);
            }
        }
    }
}
