//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UriShell.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UriShell.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setup of the object, resolved by  URI &quot;{0}&quot;, has been already done..
        /// </summary>
        internal static string AttemptToOverwriteShellResolveSetupPlayer {
            get {
                return ResourceManager.GetString("AttemptToOverwriteShellResolveSetupPlayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Icon URI &apos;{0}&apos; must be absolute..
        /// </summary>
        internal static string InvalidIconUri {
            get {
                return ResourceManager.GetString("InvalidIconUri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exceeded amount of URI, that could be opened..
        /// </summary>
        internal static string NoAvailableUriResolutionId {
            get {
                return ResourceManager.GetString("NoAvailableUriResolutionId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while opening the file &apos;{0}&apos;: {1}.
        /// </summary>
        internal static string OpenExternalFileError {
            get {
                return ResourceManager.GetString("OpenExternalFileError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to URI &quot;{0}&quot; has been opened..
        /// </summary>
        internal static string ShellResolveOpenComplete {
            get {
                return ResourceManager.GetString("ShellResolveOpenComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setup of the object , resolved via URI &quot;{0}&quot;, wasn&apos;t called due to type mismatch. Expected {1}, actual {2}..
        /// </summary>
        internal static string ShellResolveSetupAbortedDueToIncompatibility {
            get {
                return ResourceManager.GetString("ShellResolveSetupAbortedDueToIncompatibility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t set null as setup action of URI &quot;{0}&quot;..
        /// </summary>
        internal static string ShellResolveSetupPlayerCannotBeNull {
            get {
                return ResourceManager.GetString("ShellResolveSetupPlayerCannotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Перетаскивание на поддерживается в {0}..
        /// </summary>
        internal static string SidebarPlacementConnectorDoesntSupportDragDrop {
            get {
                return ResourceManager.GetString("SidebarPlacementConnectorDoesntSupportDragDrop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} не поддерживает изменение индекса присоединенного объекта. Подобное действие нецелесообразно для SidebarView..
        /// </summary>
        internal static string SidebarPlacementConnectorDoesntSupportMoveConnected {
            get {
                return ResourceManager.GetString("SidebarPlacementConnectorDoesntSupportMoveConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t perform action on {0}, because the object is busy..
        /// </summary>
        internal static string UnableToBeginChangePlacementConnector {
            get {
                return ResourceManager.GetString("UnableToBeginChangePlacementConnector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t resolve URI, because a proper resolver {0} has not been registered..
        /// </summary>
        internal static string UriModuleItemResolverNotFound {
            get {
                return ResourceManager.GetString("UriModuleItemResolverNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t place a resolved object, because no one available {0} accepted URI..
        /// </summary>
        internal static string UriPlacementNotFound {
            get {
                return ResourceManager.GetString("UriPlacementNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entry for disconnection of the object {0} hasn&apos;t been found..
        /// </summary>
        internal static string UriResolvedNotRegisteredForDisconnect {
            get {
                return ResourceManager.GetString("UriResolvedNotRegisteredForDisconnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Object {0} already exists in {1}..
        /// </summary>
        internal static string UriResolvedObjectAlreadyExists {
            get {
                return ResourceManager.GetString("UriResolvedObjectAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Object {0} doesn&apos;t exist {1}..
        /// </summary>
        internal static string UriResolvedObjectDoesntExist {
            get {
                return ResourceManager.GetString("UriResolvedObjectDoesntExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Object with ID {0} doesn&apos;t exist in  {1}..
        /// </summary>
        internal static string UriResolvedObjectIdDoesntExist {
            get {
                return ResourceManager.GetString("UriResolvedObjectIdDoesntExist", resourceCulture);
            }
        }
    }
}
